### ISSUE TITLE
Suporte a imagens

### ISSUE THREAD

**Issue by edgarberlinck** [conferencias-dev/conferencias-dev#133]
Seria bacana se os eventos pudessem ter uma imagem tanto na capa quanto la listagem. Por exemplo:

 - Na listagem: https://web.lets.events/
 - Na página do evento: https://lets.events/e/innovation-experience-ufes-em-belo-horizonte

A imagem poderia ter um tamanho fixo especificado (tipo 1905px por 1020px). Por padrão o nome da imagem pode ter o mesmo nome do arquivo do evento ou um atributo chamado `image` poderia ser informado.

O que acham?

**Comment by Arkanius** [comment]
Acho uma boa sugestão! Iremos pensar em algo do tipo. Iremos centralizar nessa issue todas as discussões a respeito dessa questão.

Obrigado!

ping @alexjjassuncao

**Comment by gabrielrufino** [comment]
Não é possível colocar imagens em markdown?

**Comment by alexjjassuncao** [comment]
Issue fechada por inatividade.
