### ISSUE TITLE
Integração com Twitter e Facebook

### ISSUE THREAD

**Issue by mustorze** [conferencias-dev/conferencias-dev#54]
Acho que seria muito bacana se tivéssemos as opções de `share`, `like` e possivelmente comentários (providos do facebook) dentro das paginas de conferencias.

Assim poderíamos interagir sobre aquela conferencia em questão e também divulga-la.

**Comment by kauanslr** [comment]
Acho que ia ser muito bom, ia agregar bastante.

**Comment by Arkanius** [comment]
@kauanslr @mustorze opa, já esta em nossos planos :)

Começaremos em breve.

**Comment by isacmoura** [comment]
Excelente ideia, ia facilitar bastante na divulgação destes eventos.

**Comment by Arkanius** [comment]
@mustorze @kauanslr @isacmoura em #59 adicionamos o Disqus que além dos comentários permite o compartilhamento no face e twitter.

Confiram lá ;)
