### ISSUE TITLE
[Ideia] Range de datas

### ISSUE THREAD

**Issue by kauanslr** [conferencias-dev/conferencias-dev#56]
Seria interessante  se fosse possível indicar um range de datas em que o evento ocorre, pois alguns aconteçem por mais de um dia.

**Comment by Arkanius** [comment]
@kauanslr obrigado pela sugestão. Isso esta no nosso backlog. Atualmente da forma que estruturamos ainda não conseguimos tratar isso, mas esta na nossa fila de prioridades

**Comment by Arkanius** [comment]
@kauanslr feito
